export const ROUTES = Object.freeze({
  LOGIN: "/login",
  STUDENT: {
    ROOT: "/student",
    DASHBOARD: "/student/dashboard",
    PROFILE: "/student/profile",
    COURSES: "/student/courses",
    ATTENDANCE: "/student/attendance",
    ASSIGNMENTS: "/student/assignments",
    EXAMINATIONS: "/student/examinations",
    RESULTS: "/student/results",
    PERFORMANCE: "/student/performance",
    SETTINGS: "/student/settings",
  },
  FACULTY: {
    ROOT: "/faculty",
    DASHBOARD: "/faculty/dashboard",
    PROFILE: "/faculty/profile",
    SUBJECTS: "/faculty/subjects",
    STUDENTS: "/faculty/students",
    ATTENDANCE: "/faculty/attendance",
    ASSIGNMENTS: "/faculty/assignments",
    EXAMINATIONS: "/faculty/examinations",
    GRADES: "/faculty/grades",
    PERFORMANCE: "/faculty/performance",
    SETTINGS: "/faculty/settings",
  },
  ADMIN: {
    ROOT: "/admin",
    DASHBOARD: "/admin/dashboard",
    STUDENTS: "/admin/students",
    FACULTY: "/admin/faculty",
    SUBJECTS: "/admin/subjects",
    NOTICES: "/admin/notices",
    SETTINGS: "/admin/settings",
  },
});
